### ISSUE TITLE
how to open in visual studio code i open in react error show

### ISSUE THREAD

**Issue by chaitanya1245** [anshuthopsee/image2pdf#1]
https://github.com/anshuthopsee/image2pdf/assets/123978162/76f9d05d-6e21-45f3-991f-97aa5418db57

**Comment by anshuthopsee** [comment]
I had accidentally spelt utils.js as utlis.js,  and that was causing that error.  I have corrected the typo now. Please make that change in your clone as well. Thanks.

**Comment by chaitanya1245** [comment]
now this error show
![Screenshot 2023-09-12 223815](https://github.com/anshuthopsee/image2pdf/assets/123978162/f470b9e4-f394-4b4e-a7da-becfbdba5889)

**Comment by anshuthopsee** [comment]
After you clone a repository you need to run "npm install" in that repository, so that all the dependencies in the package.json file get installed. In this case "jspdf" is a dependency that converts images to PDF. Please run "npm install" and let me know if the issue still persists.
