### ISSUE TITLE
error visual studio code i open in react error show  

### ISSUE THREAD

**Issue by chaitanya1245** [anshuthopsee/image2pdf#2]
![Screenshot 2023-09-12 223815](https://github.com/anshuthopsee/image2pdf/assets/123978162/3c429691-25b9-4791-9af3-4921f8bc4325)

**Comment by anshuthopsee** [comment]
After you clone a repository you need to run "npm install" in that repository, so that all the dependencies in the package.json file get installed. In this case "jspdf" is a dependency that converts images to PDF. Please run "npm install" and let me know if the issue still persists.

**Comment by chaitanya1245** [comment]
sir can you make a full video of how to install your image2pdf in Visual Studio code Otherwise, how to fix this error and send it to me, please
https://user-images.githubusercontent.com/123978162/267408191-3c429691-25b9-4791-9af3-4921f8bc4325.png
